### ISSUE TITLE
POST请求后台始终无法识别参数

### ISSUE THREAD

**Issue by cowboyfzl** [boai/BANetManager#10]
举个例子，我通过url传一个电话号码，但是后台返回给我始终是恶意请求（只有没有传参数的情况下才会返回这个）我试了另外一个框架同样的链接和参数就没这个问题，很奇怪啊，难道要给后台看那个php文件？

**Comment by huangjianguohjg** [comment]
我也遇到了这个问题

**Comment by boai** [comment]
跟后台确定下是不是请求头问题，这几天好多同学问我同样问题，后来找后台，是少了个请求头，具体还有个公共请求头，下版本我统一加上！
