### ISSUE TITLE
设置请求头的问题

### ISSUE THREAD

**Issue by ChaosLcc** [boai/BANetManager#18]
![snip20181130_1](https://user-images.githubusercontent.com/16434139/49264808-b7232c80-f48a-11e8-802e-69f60a47d512.png)

- 我这种方式设置请求头,貌似并没有设置成功, 错误信息一直是

```
    error = Unauthorized;
    message = "Full authentication is required to access this resource";
    path = "/oauth/token";
    status = 401;
    timestamp = "2018-11-30 10:12:16";
```

- 用postman请求是这样的
![snip20181130_3](https://user-images.githubusercontent.com/16434139/49264967-59dbab00-f48b-11e8-907f-9b9de0560b09.png)

**Comment by guochao285575** [comment]
![image](https://user-images.githubusercontent.com/16434139/49265410-f3578c80-f48c-11e8-8be5-6062d0c4467c.png)

**Comment by JiaoYingBo** [comment]
都散了吧，设计模式的问题，由于使用了单例，每次调接口都需要重新初始化请求头，所以外面设置的请求头就无效了
